name: Automated Unit Tests (CI)

# This tells the pipeline to run every time you push code to the main branch
on:
  push:
    branches: [ JobSeekProfileManagement]
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest

    # --- THIS IS THE FIX ---
    # It tells GitHub Actions to run the npm commands inside your project folder
    defaults:
      run:
        working-directory: ./JobSeekerProfileManagement

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Run Jest Tests
      run: npm test
